[log]=ksa.log
#[host]=nat.kanxue.com
#[udp]=0

######## SERVER CFG ########
#[nat_nic]=eth0
#[nat_tun]=0
#[dhcp_ip]=10.0.0.1
#[dhcp_mask]=255.255.255.0
#[dhcp_dns]=114.114.114.114
#[cipher]=aes_256_cfb
#[route]=
#192.168.1.0/255.255.255.0
#192.168.2.0/255.255.255.0
############################

######## CLIENT CFG ########
#[uid]=0123456789
#[psk]=password
#[tun_name]=ksa_tun
#[tun_ip]=10.0.0.2
#[fwd]=1
############################
